[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/.netlify/functions/get-content"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
